"""empty message

Revision ID: 45922b3d5573
Revises: 1fe0a043d5ac
Create Date: 2025-09-16 17:40:24.937149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45922b3d5573'
down_revision = '1fe0a043d5ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_post_id_fkey', 'user', ['post_id'], ['id'])

    # ### end Alembic commands ###
